name: gate tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test-skip-kind:
    strategy:
      matrix:
        go-version: [1.19.x, 1.20.x]
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
     - name: harden runner
       uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
       with:
         egress-policy: block
         disable-sudo: true
         allowed-endpoints: >
           github.com:443
     - name: checkout code
       uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
     - name: setup go
       uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
       with:
         go-version: ${{ matrix.go }}
     - name: run non-Kind tests
       env:
         SKIP_KIND: 1
       run: go test -v ./...
  test-all:
    strategy:
      matrix:
        go-version: [1.19.x, 1.20.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
     - name: harden runner
       uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
       with:
         egress-policy: block
         disable-sudo: true
         allowed-endpoints: >
           github.com:443
           objects.githubusercontent.com:443
           storage.googleapis.com:443
           docker.io:443
     - name: checkout code
       uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
     - name: setup go
       uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
       with:
         go-version: ${{ matrix.go }}
     - name: create KinD cluster
       uses: helm/kind-action@dda0770415bac9fc20092cacbc54aa298604d140 # v1.8.0
       with:
         cluster_name: kind
     - name: run all tests
       run: go test -v ./...
